run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive
    - goimports
  disable-all: false

linters-settings:
  goimports:
    local-prefixes: github.com/gestgo/gest
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
